[package]
name = "tetris_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#sdl2 = "0.35"
#cgmath = "*"
rand = "0.8"
bevy = "0.7"
bevy-inspector-egui = "*"